config/routes.rb
Rails.application.routes.draw do
  resources :service
  post 'service/contact'
  post  'service/metaget', to: 'service#metaget', as: 'service_metaget'
  post 'service/create'
  root to: "service#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/inquiry.rb
class Inquiry < ApplicationRecord
end

app/models/keyword.rb
class Keyword < ApplicationRecord
  has_many :service_keywords, dependent: :destroy
  has_many :services, :through => :service_keyword
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :service_keywords, dependent: :destroy
  has_many :keywords, :through => :service_keywords
end

app/models/service_keyword.rb
class ServiceKeyword < ApplicationRecord
  belongs_to :service
  belongs_to :keyword
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/service_controller.rb
class ServiceController < ApplicationController
  before_action :set_service,only: [:show,:edit,:update,:destroy]

  def index
    @services = Service.all.order("created_at DESC")
    @harf = Service.count / 2
    keyword_ary_top10 = ServiceKeyword.group(:keyword_id).order("count_all desc").limit(10).count
    @keywords = []
    keyword_ary_top10.each do |keyword|
      @keywords << Keyword.find_by(id: keyword.first)
    end
  end

  def contact
    message = params[:inquiry][:message]
    email = params[:inquiry][:email]
    inquiry = Inquiry.new(email: email, message: message)
    inquiry.save
    InquiryMailer.send_mail(inquiry).deliver_now
  end

  def create
    keywords = params[:meta][:keyword]
    @service = Service.new(service_params)
    if @service.save
      if keywords
        keywords_ary = keywords.split(" ")
        keywords_ary.each do |keyword|
          if Keyword.exists?(:name => keyword)
            word = Keyword.find_by(name: keyword)
          else
            word = Keyword.create(
              name: keyword
            )
          end
          ServiceKeyword.create(service_id: @service.id,keyword_id: word.id)
        end
      end
      redirect_to root_path
    end
  end

  def show
  end

  def edit
  end

  def update
    if @service.update(service_params)
      redirect_to @service, notice: '更新しました'
    else
      render :edit
    end
  end

  def destroy
    @service.destroy!
    redirect_to root_path, notice: '削除しました'
  end

  def metaget
    url = params[:data][:text]
    begin
      post_page = MetaInspector.new(url)
      page = MetaInspector.new(post_page.root_url)
      flash.now[:success] = "取得しました"
    rescue
      flash.now[:danger] = "取得できませんでした"
      url = "https://example.com/"
      page = MetaInspector.new(url)
    end
    keywords_ary = get_keyword(page)
    favicon = get_img(page.images.favicon,page)
    ogpimg = get_img(page.meta['og:image'],page)
    results = { :meta_url=> page.root_url,
                :meta_title => page.title,
                :meta_description => page.description,
                :meta_favicon => favicon,
                :meta_ogpimg => ogpimg,
                :meta_keyword =>keywords_ary,
                :meta_domain => page.host,
    }
    @can_add = can_add(results)
    render partial: 'metaget', locals: { :results => results }
  end

  private
  def service_params
    params.require(:service).permit(:url,:domain,:title,:description,:favicon,:ogpimg)
  end

  def set_service
    @service = Service.find(params[:id])
  end

  def get_keyword(page)
    meta_keywords = page.meta_tag['name']['keywords']
    if meta_keywords
      return meta_keywords.split(",")
    else
      return []
    end
  end

  def get_img(img,page)
    if img
      return "noimage.png" unless img.include?("png") || img.include?("jpg") || img.include?("jpeg") || img.include?("gif") || img.include?("ico")
      if img.start_with?("https") || is_ssl(page)==false
        return img
      elsif img.start_with?("http") && is_ssl(page)
        return img.sub(/http/, 'https')
      else
        return page.root_url.chop + img
      end
    else
      return "noimage.png"
    end
  end

  def is_ssl(page)
    if page.scheme == "https"
      return true
    else
      return false
    end
  end

  def can_add(results)
    if Service.exists?(:domain=>results[:meta_domain])
      return false
    elsif results[:meta_ogpimg] == "noimage.png"
      return false
    elsif results[:meta_title] && results[:meta_domain]
      return true
    else
      return false
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/service_helper.rb
module ServiceHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
  j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PBLHZ26');</script>
    <!-- End Google Tag Manager -->
    <title>サイトのMetaTag一覧 | メタギャラリー</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">
    <meta name=”description” content="様々なサイトの「title」「meta description」「meta keyword」「ogp画像」「favicon」「ドメイン」を見ることが出来るサービスです。知りたいサイトのはURLを入力して、調べてみましょう。ぜひ他社のサイトを参考にしてご自身のサイトにご活用してみて下さい。" />
    <link rel="icon" type="img/x-icon" href="/favicon.ico">

    <meta property="og:title" content="サイトのMetaTag一覧 | メタギャラリー" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= root_url%>" />
    <meta property="og:image" content="<%= root_url%>ogp_img.png" />
    <meta property="og:site_name"  content="サイトのMetaTag一覧 | メタギャラリー" />
    <meta property="og:description" content="様々なサイトの「title」「meta description」「meta keyword」「ogp画像」「favicon」「ドメイン」を見ることが出来るサービスです。知りたいサイトのはURLを入力して、調べてみましょう。ぜひ他社のサイトを参考にしてご自身のサイトにご活用してみて下さい。" />

    <!-- //Facebook用 -->
    <meta property="fb:app_id" content="220809312107669" />
    <meta property="article:publisher" content="<%= root_url%>" />

    <!-- //Twitter用 -->
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:site" content="@hatsu" />
    <meta name="twitter:title" content="サイトのMetaTag一覧 | メタギャラリー" />
    <meta name="twitter:url" content="<%= root_url%>" />
    <meta name="twitter:description" content="様々なサイトの「title」「meta description」「meta keyword」「ogp画像」「favicon」「ドメイン」を見ることが出来るサービスです。知りたいサイトのはURLを入力して、調べてみましょう。ぜひ他社のサイトを参考にしてご自身のサイトにご活用してみて下さい。" />
    <meta name="twitter:image" content="<%= root_url%>ogp_img.png" />

    <link rel="apple-touch-icon" sizes="57x57" href="favicons/apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="favicons/apple-touch-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="favicons/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="favicons/apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="favicons/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="favicons/apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="favicons/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="favicons/apple-touch-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="favicons/apple-touch-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="36x36" href="favicons/android-chrome-36x36.png">
    <link rel="icon" type="image/png" sizes="48x48" href="favicons/android-chrome-48x48.png">
    <link rel="icon" type="image/png" sizes="72x72" href="favicons/android-chrome-72x72.png">
    <link rel="icon" type="image/png" sizes="96x96" href="favicons/android-chrome-96x96.png">
    <link rel="icon" type="image/png" sizes="128x128" href="favicons/android-chrome-128x128.png">
    <link rel="icon" type="image/png" sizes="144x144" href="favicons/android-chrome-144x144.png">
    <link rel="icon" type="image/png" sizes="152x152" href="favicons/android-chrome-152x152.png">
    <link rel="icon" type="image/png" sizes="192x192" href="favicons/android-chrome-192x192.png">
    <link rel="icon" type="image/png" sizes="256x256" href="favicons/android-chrome-256x256.png">
    <link rel="icon" type="image/png" sizes="384x384" href="favicons/android-chrome-384x384.png">
    <link rel="icon" type="image/png" sizes="512x512" href="favicons/android-chrome-512x512.png">
    <link rel="icon" type="image/png" sizes="36x36" href="favicons/icon-36x36.png">
    <link rel="icon" type="image/png" sizes="48x48" href="favicons/icon-48x48.png">
    <link rel="icon" type="image/png" sizes="72x72" href="favicons/icon-72x72.png">
    <link rel="icon" type="image/png" sizes="96x96" href="favicons/icon-96x96.png">
    <link rel="icon" type="image/png" sizes="128x128" href="favicons/icon-128x128.png">
    <link rel="icon" type="image/png" sizes="144x144" href="favicons/icon-144x144.png">
    <link rel="icon" type="image/png" sizes="152x152" href="favicons/icon-152x152.png">
    <link rel="icon" type="image/png" sizes="160x160" href="favicons/icon-160x160.png">
    <link rel="icon" type="image/png" sizes="192x192" href="favicons/icon-192x192.png">
    <link rel="icon" type="image/png" sizes="196x196" href="favicons/icon-196x196.png">
    <link rel="icon" type="image/png" sizes="256x256" href="favicons/icon-256x256.png">
    <link rel="icon" type="image/png" sizes="384x384" href="favicons/icon-384x384.png">
    <link rel="icon" type="image/png" sizes="512x512" href="favicons/icon-512x512.png">
    <link rel="icon" type="image/png" sizes="16x16" href="favicons/icon-16x16.png">
    <link rel="icon" type="image/png" sizes="24x24" href="favicons/icon-24x24.png">
    <link rel="icon" type="image/png" sizes="32x32" href="favicons/icon-32x32.png">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css">
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0&#45;rc.2/js/materialize.min.js"></script> -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="manifest" href="/manifest.json" />
    <meta name="apple-mobile-web-app-capable" content="yes"></head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.lazyload/1.9.1/jquery.lazyload.min.js"></script>

  <body>
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PBLHZ26"
                      height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->
    <header>
      <i class="fas fa-code"></i>
      <h1>Metagallery</h1>
    </header>

    <div id="fixed_header">
      <div class="header_text_block">
        <i class="fas fa-columns"></i>
        <i class="far fa-square"></i>
        <h2>Metagallery</h2>
        <i class="fas fa-search form_to_appear"></i>
      </div>
      <div class="service_search_form_block">
        <div class="service_search_form_cover">
          <i class="fas fa-search form_to_close"></i>
          <form id="service_search_form" action="/" onsubmit="document.activeElement.blur();return false;">
            <input id="service_search_input" type="search" placeholder="キーワード検索">
            <label for="service_search_input"></label>
          </form>
        </div>
      </div>
    </div>


    <%= yield %>
    <footer>
      <h2>シェアする</h2>
      <div class="ziguzagu_block">
        <img src="ziguzagu.png">
      </div>
      <!-- <div class="footer_border_top"></div> -->
      <ul class="sns_block row">
        <li class="col s4">
          <a href="https://twitter.com/share?url=<%= root_url %>&text=サイトのMetaTag一覧 - メタギャラリー" target="_blank" class="twitter sns">
            <i class="fab fa-twitter"></i>
          </a>
        </li>
        <li class="col s4">
          <a href="https://www.facebook.com/share.php?u=<%= root_url %>&text=サイトのMetaTag一覧 | メタギャラリー" target="_blank" class="facebook sns">
            <i class="fab fa-facebook-f"></i>
          </a>
        </li>
        <li class="col s4">
          <a href="http://b.hatena.ne.jp/entry/<%= root_url %>" data-hatena-bookmark-layout="touch" title="このエントリーをはてなブックマークに追加" target="_blank" class="hatena sns">
            B!
          </a>
        </li>
      </ul>
      <div class="info_block">
        <a href="https://twitter.com/hatsu_38" target="_blank"><i class="fas fa-play-circle"></i>運営者</a>
      </div>
      <p class="footer_copy">
      © Copyright 2018 hastu All rights reserved.
      </p>
    </footer>
    <span class="fa-stack sort_top_btn">
      <i class="fa fa-circle fa-stack-2x"></i>
      <i class="fas fa-sort-up fa-stack-1x fa-inverse"></i>
    </span>

    <button data-target="contact_form" class="btn modal-trigger right contact_modal_btn">
      <i class="far fa-envelope"></i>ご意見箱
    </button>
    <div id="contact_form" class="modal">
      <h3 class="title">ご意見・ご感想はこちら</h3>
      <div class="flash_message contact_flash">ご意見ありがとうございました。</div>
      <div class="contact_message_block">
        <p class="contact_message">メタギャラリーをご利用頂きありがとうございます。</p>
        <p class="contact_message">メタギャラリーをより使いやすいサービスにするため、ご意見を募集しております。</p>
        <p class="contact_message">ご不明点やご意見がございましたら、フォームよりご連絡ください。<span class="emphasis">メッセージはすべて匿名で送られます</span>のでご安心ください。</p>
      </div>
      <%= form_tag(service_contact_path, method: :post, remote: true, class: "row") { %>
        <div class="input-field message_form">
          <i class="fas fa-pencil-alt prefix"></i>
          <%= text_area :inquiry, :message,:class => "materialize-textarea validate_input contact_form_area", :id => "icon_prefix2", :placeholder => "" %>
          <label for="icon_prefix2">ご意見をご記入ください</label>
        </div>

        <div class="input-field message_form">
          <i class="far fa-envelope prefix"></i>
          <%= text_field :inquiry, :email,:class => "contact_form_area", :id => "icon_prefix2",:placeholder => "example@cafepedia.com" %>
          <label for="icon_prefix2" class="mail_label active">返信を希望する場合はメールアドレスをご記入ください</label>
        </div>
        <div class="submit_btn_cover center">
          <%= submit_tag '送信する' ,:class => "btn contact_send_btn",:id=>"contact_submit",:disabled=>true %>
        </div>
      <% } %>
    </div>
    <script>
$(function(){
  $(document).ready(function(){
    $('.modal').modal();
    $('.lazy').lazyload({
      effect: 'fadeIn',
      effectspeed: 100,
      threshold :300,
    });
  });

  $("#contact_form .validate_input").on("keydown keyup keypress change", function() {
    if ($(this).val()) {
      $("#contact_form .contact_send_btn").prop("disabled", false);
    } else {
      $("#contact_form .contact_send_btn").prop("disabled", true);
    }
  });
  $('#contact_form').on('ajax:send',function(data, status, xhr){
    $('#contact_submit').val('送信中').attr({disabled: true});
  });
  $('#contact_form').on('ajax:success',function(data, status, xhr){
    $('#contact_submit').val('送信する').attr({disabled: false});
    $('.contact_flash').fadeIn();
    $('.contact_flash').delay(4000).fadeOut();
  });
});
    </script>
  </body>
</html>

app/views/service/_form.html.erb
<%= form_for(@service) do |f| %>
  <div class="input-field">
    <%= f.text_field :ogpimg,:id=>"ogp_val"  %>
    <%= f.label:ogpimg,:id=>"ogp_val" ,:class=>"active" %>
  </div>
  <div class="input-field">
    <%= f.text_field :domain %>
    <%= f.label:domain,:class=>"active" %>
  </div>
  <div class="input-field">
    <%= f.text_field :title %>
    <%= f.label:title,:class=>"active" %>
  </div>
  <div class="input-field">
    <%= f.text_field :description %>
    <%= f.label:description,:class=>"active" %>
  </div>
  <div class="input-field">
    <%= f.text_field :favicon %>
    <%= f.label:favicon,:class=>"active" %>
  </div>
  <div class="center">
    <%= submit_tag "更新する",class: 'btn' %>
  </div>
<% end %>

app/views/service/_metaget.html.erb
<div id="ogp_result" class="service">
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>
  <div class="service_block">
    <div class="card">
      <div class="thumbnail card-image">
        <img src="<%= results[:meta_ogpimg] %>" class="ogp_img">
      </div>
      <div class="card-content">
        <p class="service_title card-title"><%= results[:meta_title] %></p>
        <p class="description"><%= results[:meta_description] %></p>
        <% results[:meta_keyword].each do |keyword| %>
          <span class="chip"><%= keyword %></span>
        <% end %>
        <p class="domain">
          <img src="<%= results[:meta_favicon] %>" class="favicon">
          <a href="<%= results[:meta_url] %>" target="_blank"><%= results[:meta_domain] %></a>
        </p>
      </div>
    </div>
  </div>
</div>

<div id="loading">
  <img src="loading.gif">
</div>

<%= form_tag(service_create_path, method: :post) { %>
  <%= hidden_field :service,:name,:value => results[:meta_title] %>
  <%= hidden_field :service,:url,:value => results[:meta_url],:id=>"ogp_val"  %>
  <%= hidden_field :service,:domain,:value => results[:meta_domain] %>
  <%= hidden_field :service,:title,:value => results[:meta_title] %>
  <%= hidden_field :service,:description ,:value => results[:meta_description] %>
  <%= hidden_field :service,:favicon,:value => results[:meta_favicon] %>
  <%= hidden_field :service,:ogpimg,:value => results[:meta_ogpimg] %>
  <%= hidden_field :meta,:keyword,:value => results[:meta_keyword] %>
  <%= submit_tag "追加する",class: 'btn' if @can_add %>
<% } %>

app/views/service/edit.html.erb
<h2 class="center">編集する</h2>

<%= render 'form', service: @service %>

app/views/service/index.html.erb
<section id="search">
  <div class="search_ogp">
    <div id="request_ajax_update" >
      <%= form_tag(service_metaget_path, method: :post, remote: true, class: "row") { %>
        <%= text_field :data, :text ,:class => "col s9",:placeholder => "https://example.com" %>
        <%= submit_tag '調べる' ,:class => "btn col s3 search_btn",:disabled => true %>
      <% } %>
    </div>

    <div id="example_ogp" class="service">
      <div class="service_block">
        <div class="card">
          <div class="thumbnail card-image">
            <img src="noimage.png" class="ogp_img">
          </div>
          <div class="card-content">
            <p class="service_title card-title">Metagallery</p>
            <p class="description">metaDescriptionが表示されます。主にサービスの概要が書かれます。上にはサイトタイトル、ogp画像。下にはメタキーワード、favicon、ドメインが表示されます。</p>
            <span class="chip">Metagallery</span>
            <span class="chip">メタギャラリー</span>
            <span class="chip">keyword</span>
            <p class="domain">
            <img src="noimage.png" class="favicon">
            <a href="http://www.metagallery.jp/" target="_blank">www.metagallery.jp</a>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section id="keywords">
  <div id="keywords_scroll_block">
    <h2 class="keyword_title">おすすめキーワード</h2>
    <div class="ziguzagu_block">
      <img src="ziguzagu.png">
    </div>
    <ul class="slide simplyScroll" id="keywords_scroll">
      <li class="chip filter" data-filter="all">全部</li>
      <% @keywords.each do |keyword| %>
        <li class="keyword chip filter" data-filter=".<%= keyword.name %>">
          #<%= keyword.name %>
        </li>
      <% end %>
    </ul>
  </div>
</section>

<section id="gallery">
  <h2 class="gallery">ギャラリー</h2>
  <div class="ziguzagu_block">
    <img src="ziguzagu.png">
  </div>
  <p class="no_service_msg">対象のキーワードのサービスはありません</p>
  <div id="service_index">
    <% @services.each_with_index do |service,i| %>
      <div class="mix service <%= service.keywords.pluck(:name).join(" ") %>">
        <div class="service_block">
          <div class="card">
            <div class="thumbnail card-image">
              <% if i >=@harf && i < (@harf * 2)-13 %>
                <img src="<%= service.ogpimg %>" class="ogp_img">
              <% else %>
                <img src="loading.gif" data-original="<%= service.ogpimg %>" class="ogp_img lazy">
              <% end %>
            </div>
            <div class="card-content">
              <p class="service_title card-title"><%= service.title %></p>
              <p class="description"><%= service.description %></p>
              <% service.keywords.each do |keyword|  %>
                <span class="chip"><%= keyword.name %></span>
              <% end %>
              <p class="domain">
                <img src="<%= service.favicon %>" class="favicon">
                <a href="<%= service.url%>" target="_blank"><%= service.domain %></a>
              </p>
              <span style="display:none;"><%= service.id %></span>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <div class="gap"></div>
    <div class="gap"></div>
  </div>
</section>

<section id="about">
  <h2 class="about">メタギャラリーとは</h2>
  <div class="ziguzagu_block">
    <img src="ziguzagu.png">
  </div>
  <p>様々なサイトの<span class="emphasis">「title」「meta description」「meta keyword」「ogp画像」「favicon」「ドメイン」</span>を見ることが出来るサービスです。知りたいサイトのはURLを入力して、調べてみましょう。ぜひ他社のサイトを参考にしてご自身のサイトにご活用してみて下さい！</p>
</section>

app/views/service/show.html.erb
<div class="mix service <%= @service.keywords.pluck(:name).join(" ") %>">
  <div class="service_block">
    <div class="card">
      <div class="thumbnail card-image">
        <img src="<%= @service.ogpimg %>" class="ogp_img">
      </div>
      <div class="card-content">
        <p class="service_title card-title"><%= @service.title %></p>
        <p class="description"><%= @service.description %></p>
        <% @service.keywords.each do |keyword|  %>
          <span class="chip"><%= keyword.name %></span>
        <% end %>
        <p class="domain">
        <img src="<%= @service.favicon %>" class="favicon">
        <a href="<%= @service.url%>" target="_blank"><%= @service.domain %></a>
        </p>
      </div>
    </div>
  </div>
</div>

<div class="center">
  <%= link_to '編集', edit_service_path(@service), class: 'btn waves-effect waves-light' %>
  <%= link_to '削除', service_path(@service),method: :DELETE,data:{confirm: "「#{@service.title}」を削除しますか？"}, class: 'btn waves-effect waves-light' %>
</div>